[lib]
crate-type = ["cdylib", "lib"]
name = "hello_world"

[package]
edition = "2021"
name = "hello_world"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.15.2"
solana-test-validator = "1.15.2"
